---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-from-env-files
data:
  # Database connection params
  NAUTOBOT_DB_HOST: postgres
  NAUTOBOT_DB_USER: nautobot
  NAUTOBOT_DB_NAME: nautobot
  # Postgres configuration params
  POSTGRES_DB: nautobot
  POSTGRES_USER: nautobot
  # Redis connection params
  NAUTOBOT_REDIS_HOST: redis
  # Nautobot configuration
  NAUTOBOT_ALLOWED_HOSTS: "*"
  NAUTOBOT_LOG_LEVEL: DEBUG